replicaCount:
  min: 1
  max: 3
  desired: 2

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: true
  hostname: nginx.local

redis:
  host: "redis-system.desafio-devops-redis"
  port: 6379

content:
  message: "Hello World"